### PR TITLE
Split out gun

### PR DESCRIPTION
**Pull request by Dletta**
Test it here: https://dletta-meething.glitch.me/

I just split out gun, initialize it earlier and add the peer later when we know what to connect to

### CODE REVIEW

**Comment by QVDev** [comment]
Like this, will test this a bit

**Comment by QVDev** [comment]
@Dletta joining seems to fail when you first open the settings page:

`Uncaught (in promise) ReferenceError: room is not defined
    at Room.join (room.js:28)
    at SFU.joinRoom (sfu.js:56)
    at Video.loadSimpleWebRTC (video.js:41)
    at Video.establish (video.js:16)
    at Connection.establish (connection.js:44)
    at Mediator.initComm (main.js:114)
    at modal.js:55
    at ee.js:16
    at Array.forEach (<anonymous>)
    at EventEmitter.emit (ee.js:16)`

Should be changed to roomId

**Comment by Dletta** [comment]
I actually encountered it and didn’t have the courage to change it. :)

**Comment by QVDev** [comment]
@Dletta you can do it :) change it :)

**Comment by Dletta** [comment]
Rebased and ready for merge @QVDev and @lmangani. Doesn't have to be before Mentor call

**Pull request merged**
