### PR TITLE
Add simple snackbar to notify users

### PR DESCRIPTION
**Pull request by QVDev**
notification

### CODE REVIEW

**Comment by lmangani** [comment]
Really nice! shall we move the joining info and other notifications to this too rather than the chat?

**Comment by QVDev** [comment]
> Really nice! shall we move the joining info and other notifications to this too rather than the chat?

Maybe that is too much information? As you see people appearing with vide and there soon to be username. Don't think we need a notification for every user joining

**Comment by Dletta** [comment]
2 comments,

1. Question: Should it be a little bit bigger? 

2. OffGrid and onGrid will be the whole room, maybe we should set the notification to be ‘Room is going offGrid’ ?

**Comment by QVDev** [comment]
@Dletta thanks for the feedback

- will make it a bit bigger text and area
- problem is ongrid we cant switch everyone to ongrid as nobody received the message ;)

**Comment by QVDev** [comment]
@Dletta Made the font bigger so it will better visible. Think other css master improve it later.

Will wait for the offgrid mode until we are clear how we handle onGrid :) for now it will just give a notification

**Comment by jacovinus** [comment]
Awesome! if there is a need of styling will not be a problem ;)
just one thing is that every div should go before the script tags at bottom .
Later that toast can be placed anywhere, the important thing is to have it. 👍

**Pull request merged**
