### PR TITLE
Add a simple remote debug logger via gun

### PR DESCRIPTION
**Pull request by QVDev**
Visit /log.html to see all the logs, it replaces the current log directly once you put 

`<script src="assets/js/gunlogger.js"></script>`

in the one that should report

### CODE REVIEW

**Comment by QVDev** [comment]
Please check here 

https://meething-qvdev.herokuapp.com/

double test if you hear yourself so try wit other particpants

**Comment by jabis** [comment]
Maybe wrap this into the event emitter- pattern - I think it's still valid concearn

**Comment by Dletta** [comment]
Yes, I’ve been thinking about passing debug around so you only have to put debug true once...?

**Comment by QVDev** [comment]
Not needed at the moment

**Pull request closed without merging**
