### PR TITLE
WIP PR Graph

### LINKED ISSUE #73: Connection Graph Widget / Maybe Background
- [x] D3 render graph
- [x] Move sim to webworker
- [ ] integrate into a class that consumes network msg from presence.js

This is to show who we are connected with in the room.
Future addon would be to show all connected people in the lobby across the global network.
Although not power hungry at all, webworker will make sure we don't bog down the main thread

### PR DESCRIPTION
**Pull request by Dletta**
Okay, workerGraph.js added to a worker folder in assets.
Currently I am showing index.html modifications so you can uncomment them to see it in action.

2 future things for integration
- [x] need to add window height and width into the object sent to worker so we an center graph
- [x] create graph based on actual data received from @QVDev 

Resolves #73 

Please look over, we need to figure out where to put the code now in index.html (e.g. presence.js?), where we have enough scope to access the document size (so we can scale graph based on that) but also have access to events that need change in the graph (e.g. new connections made, lost, name changes, window resize)

Currently generation of graphs is super fast (around 500 ms), if needed I could provide events back to mainthread to show a progress bar, but not necessary currently. If we pass a fake node at onload of the page, the background image idea could show 1 node, but it would be hidden behind the menu, which is also a problem right now for the normal graph. We could have a seperate route for a widget so we can see it there.

Arrows are sadly not the same color as the edges, but unless SVG 2.0 comes out any time soon, I don't expect that I can change that at this point...

### CODE REVIEW

**Comment by Dletta** [comment]
I recommend rtc.js hook with latest commit, I will consume pcmap and turn it into an edge. This will mean that for now, you will only see who you are connected to, but that's okay.

Actually comparing pcMap.size against self.users.length could fire an automatic re-invite, @QVDev @lmangani

**Comment by QVDev** [comment]
@Dletta you suggest to re invite upon comparison?

**Comment by Dletta** [comment]
@QVDev I saw the user list is always shared with the others via DAM, while I had a missing stream and needed to reinvite to see it. The user list was definitely showing the 5 streams, while pcMap was not showing the missing one (aka because I was not connected)

**Comment by lmangani** [comment]
@Dletta this was one of the original purposes, to detect and renegotiate missing connections over a known map of them all. In theory upon disconnections we can check the graph for missing links and send a subscribe or tailored subscribe even (with to: field)

**Comment by QVDev** [comment]
But also have to be aware that currently the presence is not the most stable. Due to how people leave a room. So there might be a person in the user list that actual leaves but re invite wont work than. But if we may catch that we can improve the list as well.

**Comment by Dletta** [comment]
This can be behind the scenes, as in user won’t know that we are reinviting. But yeah, I want to build the graph in gun with an index, then presence can be more accurate

**Comment by Dletta** [comment]
Try it here: https://meething-webrtc-dletta.glitch.me/?room=test (in two tabs)

For now it's just using info from pcMap, I'd love to have the usernames there, but not currently in pcMap.

**Pull request merged**
